version: 2.1
orbs:
  # import Cypress orb by specifying an exact version x.y.z
  # or the latest version 1.x.x using "@1" syntax
  cypress: cypress-io/cypress@1
executors:
  base-12:
    docker:
      - image: 'cypress/base:14.21.1'
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          yarn: true
          start: npm i -force && npm run start
          wait-on: 'http://localhost:3000'
          command: npx percy exec -- cypress run 
          # no need to save this workspace - ther e are no jobs after this one
          no-workspace: true
          executor: base-12
